version: '4'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - .:/var/www/kuba.moscow
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    links:
      - php

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/kuba.moscow
    links:
      - db

  db:
    image: mysql:latest
    container_name: db_mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_TCP_PORT: 3307
